import { FormConnect } from "@/components/FormConnect";
import { BtnLogout } from "@/components/ui/btn_logout";
import { SidebarTab } from "@/components/ui/link";
import { getUser } from "@/db/controllers/user.controller";
import { Heart, LogOut, MapPin, Package, Settings, User } from "lucide-react";
import type { Metadata } from "next";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getUser()
    return (

        <section>
            <div className="flex items-center justify-between">
                <h2 className="text-2xl font-bold">Mon compte</h2>
                {user ? (
                    <BtnLogout>
                        <LogOut className="w-4 h-4" /> Déconnexion
                    </BtnLogout>
                ) :
                    null}
            </div>
            {!user ? (
                <div className="mt-6">
                    <FormConnect />
                </div>
            ) : (
                <div className="mt-6 grid lg:grid-cols-4 gap-6">
                    <div className="lg:col-span-1 space-y-2">
                        <SidebarTab  link="/account"><User className="w-4 h-4" /> Profil </SidebarTab>
                        <SidebarTab   link="/account/orders">Commandes <Package  className="w-4 h-4"/></SidebarTab>
                        <SidebarTab link="/account/addresses">  <MapPin className="w-4 h-4" />   Adresses </SidebarTab>
                        <SidebarTab  link="/account/favorites">
                          <Heart  className="w-4 h-4" /> Favoris</SidebarTab>
                        <SidebarTab link="/account/settings"><Settings  className="w-4 h-4"/> Paramètres</SidebarTab>
                    </div>

                    <div className="lg:col-span-3">
                

                      
                        {children} 

                        
                    </div>
                </div>
            )}
        </section>

    );
}


